# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 274)
        self.fsuipc = QtWidgets.QGroupBox(Form)
        self.fsuipc.setGeometry(QtCore.QRect(10, 190, 381, 61))
        self.fsuipc.setObjectName("fsuipc")
        self.statusLabel = QtWidgets.QLabel(self.fsuipc)
        self.statusLabel.setGeometry(QtCore.QRect(10, 20, 161, 21))
        self.statusLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.statusLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setWordWrap(True)
        self.statusLabel.setObjectName("statusLabel")
        self.connectButton = QtWidgets.QPushButton(self.fsuipc)
        self.connectButton.setGeometry(QtCore.QRect(190, 20, 75, 23))
        self.connectButton.setObjectName("connectButton")
        self.disconnectButton = QtWidgets.QPushButton(self.fsuipc)
        self.disconnectButton.setGeometry(QtCore.QRect(280, 20, 75, 23))
        self.disconnectButton.setObjectName("disconnectButton")
        self.presence = QtWidgets.QGroupBox(Form)
        self.presence.setGeometry(QtCore.QRect(10, 10, 381, 171))
        self.presence.setObjectName("presence")
        self.depLine = QtWidgets.QLineEdit(self.presence)
        self.depLine.setGeometry(QtCore.QRect(70, 20, 51, 20))
        self.depLine.setMaxLength(4)
        self.depLine.setObjectName("depLine")
        self.depLabel = QtWidgets.QLabel(self.presence)
        self.depLabel.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.depLabel.setObjectName("depLabel")
        self.arrLabel = QtWidgets.QLabel(self.presence)
        self.arrLabel.setGeometry(QtCore.QRect(10, 50, 51, 21))
        self.arrLabel.setObjectName("arrLabel")
        self.arrLine = QtWidgets.QLineEdit(self.presence)
        self.arrLine.setGeometry(QtCore.QRect(70, 50, 51, 20))
        self.arrLine.setMaxLength(4)
        self.arrLine.setObjectName("arrLine")
        self.cruiseLine = QtWidgets.QLineEdit(self.presence)
        self.cruiseLine.setGeometry(QtCore.QRect(70, 80, 61, 20))
        self.cruiseLine.setMaxLength(5)
        self.cruiseLine.setObjectName("cruiseLine")
        self.airframeLine = QtWidgets.QLineEdit(self.presence)
        self.airframeLine.setGeometry(QtCore.QRect(70, 110, 51, 20))
        self.airframeLine.setMaxLength(4)
        self.airframeLine.setObjectName("airframeLine")
        self.cruiseLabel = QtWidgets.QLabel(self.presence)
        self.cruiseLabel.setObjectName("cruiseLabel")
        self.cruiseLabel.setGeometry(QtCore.QRect(10, 80, 51, 21))
        self.ftLabel = QtWidgets.QLabel(self.presence)
        self.ftLabel.setGeometry(QtCore.QRect(140, 80, 16, 21))
        self.ftLabel.setObjectName("ftLabel")
        self.airframeLabel = QtWidgets.QLabel(self.presence)
        self.airframeLabel.setGeometry(QtCore.QRect(10, 110, 51, 21))
        self.airframeLabel.setObjectName("airframeLabel")
        self.callLine = QtWidgets.QLineEdit(self.presence)
        self.callLine.setGeometry(QtCore.QRect(250, 20, 111, 20))
        self.callLine.setMaxLength(10)
        self.callLine.setObjectName("callLine")
        self.networkLabel = QtWidgets.QLabel(self.presence)
        self.networkLabel.setGeometry(QtCore.QRect(190, 50, 47, 21))
        self.networkLabel.setObjectName("networkLabel")
        self.networkCombo = QtWidgets.QComboBox(self.presence)
        self.networkCombo.setGeometry(QtCore.QRect(250, 50, 111, 22))
        self.networkCombo.setObjectName("networkCombo")
        self.simLabel = QtWidgets.QLabel(self.presence)
        self.simLabel.setGeometry(QtCore.QRect(190, 80, 47, 21))
        self.simLabel.setObjectName("simLabel")
        self.simCombo = QtWidgets.QComboBox(self.presence)
        self.simCombo.setGeometry(QtCore.QRect(250, 80, 111, 22))
        self.simCombo.setObjectName("simCombo")
        self.simCombo.addItem("")
        self.simCombo.addItem("")
        self.simCombo.addItem("")
        self.callLabel = QtWidgets.QLabel(self.presence)
        self.callLabel.setGeometry(QtCore.QRect(190, 20, 51, 21))
        self.callLabel.setObjectName("callLabel")
        self.startButton = QtWidgets.QPushButton(self.presence)
        self.startButton.setGeometry(QtCore.QRect(190, 110, 171, 23))
        self.startButton.setObjectName("startButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "FSRP2"))
        self.fsuipc.setTitle(_translate("Form", "FSUIPC"))
        self.statusLabel.setText(_translate("Form", "Not connected to FSUIPC"))
        self.connectButton.setText(_translate("Form", "Connect"))
        self.disconnectButton.setText(_translate("Form", "Disconnect"))
        self.presence.setTitle(_translate("Form", "Presence"))
        self.depLabel.setText(_translate("Form", "Departure"))
        self.arrLabel.setText(_translate("Form", "Arrival"))
        self.cruiseLabel.setText(_translate("Form", "Cruise alt."))
        self.ftLabel.setText(_translate("Form", "ft"))
        self.networkLabel.setText(_translate("Form", "Network"))
        self.simLabel.setText(_translate("Form", "Simulator"))
        self.simCombo.setItemText(0, _translate("Form", "FSX"))
        self.simCombo.setItemText(1, _translate("Form", "P3D"))
        self.simCombo.setItemText(2, _translate("Form", "X-Plane"))
        self.airframeLabel.setText(_translate("Form", "Airframe"))
        self.callLabel.setText(_translate("Form", "Callsign"))
        self.startButton.setText(_translate("Form", "Start presence"))

